use_starship = true
path = ["/home/rochacbruno/bin", "/usr/local/bin", "/home/rochacbruno/.poetry/bin", "/home/rochacbruno/.bin", "/home/rochacbruno/.cargo/bin", "/home/rochacbruno/.local/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/local/sbin", "/usr/lib/jvm/default/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl", "/var/lib/snapd/snap/bin", "/home/rochacbruno/.cargo/bin", "/home/rochacbruno/.poetry/bin", "/home/rochacbruno/.poetry/bin", "/home/rochacbruno/.bin", "/home/rochacbruno/.cargo/bin", "/home/rochacbruno/.local/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/local/sbin", "/usr/lib/jvm/default/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl", "/var/lib/snapd/snap/bin"]

[env]
COLORTERM = "truecolor"
GDMSESSION = "i3"
LANG = "en_US.UTF-8"
XDG_CURRENT_DESKTOP = "i3"
TERM = "xterm-256color"
LC_IDENTIFICATION = "pt_BR.UTF-8"
TILIX_ID = "ed46e9c9-1e81-4b2d-8b46-66aa8ba42fea"
XDG_GREETER_DATA_DIR = "/var/lib/lightdm-data/rochacbruno"
LC_MEASUREMENT = "pt_BR.UTF-8"
USER = "rochacbruno"
XDG_SESSION_PATH = "/org/freedesktop/DisplayManager/Session0"
DESKTOP_SESSION = "i3"
HOME = "/home/rochacbruno"
XDG_VTNR = "7"
XDG_SEAT = "seat0"
I3SOCK = "/run/user/1000/i3/ipc-socket.1485"
LC_NUMERIC = "pt_BR.UTF-8"
GTK_MODULES = "canberra-gtk-module"
XDG_DATA_DIRS = "/usr/local/share:/usr/share:/var/lib/snapd/desktop"
VTE_VERSION = "6003"
XDG_SESSION_DESKTOP = "i3"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
BROWSER = "/usr/bin/google-chrome-stable"
LC_TIME = "pt_BR.UTF-8"
MAIL = "/var/spool/mail/rochacbruno"
XDG_SEAT_PATH = "/org/freedesktop/DisplayManager/Seat0"
LOGNAME = "rochacbruno"
LC_PAPER = "pt_BR.UTF-8"
XDG_RUNTIME_DIR = "/run/user/1000"
_ = "/home/rochacbruno/.cargo/bin/nu"
SHELL = "/usr/bin/zsh"
XDG_SESSION_TYPE = "x11"
LC_MONETARY = "pt_BR.UTF-8"
GTK2_RC_FILES = "/home/rochacbruno/.gtkrc-2.0"
LC_TELEPHONE = "pt_BR.UTF-8"
EDITOR = "/home/rochacbruno/bin/micro"
XDG_SESSION_ID = "2"
QT_QPA_PLATFORMTHEME = "qt5ct"
SHLVL = "1"
XAUTHORITY = "/home/rochacbruno/.Xauthority"
LC_NAME = "pt_BR.UTF-8"
DISPLAY = ":0"
XDG_SESSION_CLASS = "user"
PWD = "/opt/discord/Discord"
LC_ADDRESS = "pt_BR.UTF-8"
OLDPWD = "/opt/discord"
ZSH = "/home/rochacbruno/.oh-my-zsh"
PAGER = "less"
LESS = "-R"
LSCOLORS = "Gxfxcxdxbxegedabagacad"
LS_COLORS = "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
VIRTUAL_ENV_DISABLE_PROMPT = "1"
_VIRTUALENVWRAPPER_API = " mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv wipeenv allvirtualenv"
VIRTUALENVWRAPPER_SCRIPT = "/usr/bin/virtualenvwrapper.sh"
VIRTUALENVWRAPPER_PYTHON = "/usr/bin/python3.8"
STARSHIP_SHELL = ""
VIRTUALENVWRAPPER_PROJECT_FILENAME = ".project"
VIRTUALENVWRAPPER_WORKON_CD = "1"
WORKON_HOME = "/home/rochacbruno/.virtualenvs"
VIRTUALENVWRAPPER_HOOK_DIR = "/home/rochacbruno/.virtualenvs"
