config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_gromit-mpx.cfg:
    src: config/gromit-mpx.cfg
    dst: ~/.config/gromit-mpx.cfg
  f_gromit-mpx.ini:
    src: config/gromit-mpx.ini
    dst: ~/.config/gromit-mpx.ini
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_pypirc:
    src: pypirc
    dst: ~/.pypirc
  f_kdenlive-layoutsrc:
    src: config/kdenlive-layoutsrc
    dst: ~/.config/kdenlive-layoutsrc
    chmod: '600'
  f_kdenliverc:
    src: config/kdenliverc
    dst: ~/.config/kdenliverc
    chmod: '600'
  d_obs-studio:
    src: config/obs-studio
    dst: ~/.config/obs-studio
    cmpignore:
    - profiler_data/*
    - logs/*
    upignore:
    - profiler_data/*
    - logs/*
  d_terminator:
    src: config/terminator
    dst: ~/.config/terminator
  d_bin:
    src: bin
    dst: ~/bin
    cmpignore:
    - kubectl
    - ctlptl
    - gitleaks
    - oc
    - codacy-coverage-reporter
    - lapce
    - antares
    upignore:
    - kubectl
    - ctlptl
    - gitleaks
    - oc
    - codacy-coverage-reporter
    - lapce
    - antares
  f_bindings.json:
    src: config/micro/bindings.json
    dst: ~/.config/micro/bindings.json
  f_init.lua:
    src: config/micro/init.lua
    dst: ~/.config/micro/init.lua
  f_installed_plugins.txt:
    src: config/micro/installed_plugins.txt
    dst: ~/.config/micro/installed_plugins.txt
  f_micro_settings.json:
    src: config/micro/settings.json
    dst: ~/.config/micro/settings.json
  d_thunar:
    src: config/Thunar
    dst: ~/.config/Thunar
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_zsh:
    src: zsh
    dst: ~/.zsh
  d_themes:
    src: config/obs-studio/themes
    dst: ~/.config/obs-studio/themes
  d_flameshot:
    src: config/flameshot
    dst: ~/.config/flameshot
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_kate:
    src: config/kate
    dst: ~/.config/kate
  f_katerc:
    src: config/katerc
    dst: ~/.config/katerc
    chmod: '600'
  f_katevirc:
    src: config/katevirc
    dst: ~/.config/katevirc
    chmod: '600'
  f_katemetainfos:
    src: config/katemetainfos
    dst: ~/.config/katemetainfos
    chmod: '600'
  f_kdeglobals:
    src: config/kdeglobals
    dst: ~/.config/kdeglobals
    chmod: '600'
  f_kateschemarc:
    src: config/kateschemarc
    dst: ~/.config/kateschemarc
    chmod: '600'
  d_kxmlgui5_kate:
    src: local/share/kxmlgui5/kate
    dst: ~/.local/share/kxmlgui5/kate
  d_katepart:
    src: local/share/kxmlgui5/katepart
    dst: ~/.local/share/kxmlgui5/katepart
  d_kateproject:
    src: local/share/kxmlgui5/kateproject
    dst: ~/.local/share/kxmlgui5/kateproject
  f_kglobalshortcutsrc:
    src: config/kglobalshortcutsrc
    dst: ~/.config/kglobalshortcutsrc
    chmod: '600'
profiles:
  rocha:
    dotfiles:
    - f_bashrc
    - f_gitconfig
    - f_gitignore
    - f_gtkrc-2.0
    - f_zshrc
    - f_pypirc
    - f_kdenlive-layoutsrc
    - f_kdenliverc
    - d_obs-studio
    - d_terminator
    - d_bin
    - f_bindings.json
    - f_init.lua
    - f_installed_plugins.txt
    - f_micro_settings.json
    - d_thunar
    - f_pacman.conf
    - d_bat
    - d_zsh
    - d_themes
    - d_flameshot
    - f_starship.toml
    - d_kate
    - f_katerc
    - f_katevirc
    - f_katemetainfos
    - f_kdeglobals
    - f_kateschemarc
    - d_kxmlgui5_kate
    - d_katepart
    - d_kateproject
    - f_kglobalshortcutsrc
