author: Dominique Da Silva
description: Lorem ipsum sentences and paragraphs generator.
name: lorem
title: Lorem Ipsum
version: 0.1.0
homepage: "https://github.com/atika/espanso-lorem"
tags: ["lorem", "design", "utility"]