author: FoxxMD
description: All emojis, with alt names, provided by gemoji
name: all-emojis
title: All Emojis
version: 0.1.0
homepage: "https://github.com/FoxxMD/espanso-all-emojis"
tags: ["emoji", "chat"]