theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R in 🇵🇹"
on_click = "orage"
