theme = "gruvbox-dark"
icons = "awesome"


# [[block]]
# block = "music"
# # player = "spotify"
# buttons = ["play", "next"]
# on_collapsed_click = "spotify"

# [[block]]
# block = "net"
# device = "enp0s31f6"
# # ssid = truer
# # signal_strength = true
# # ip = true
# speed_up = true
# graph_up = true
# interval = 5
# use_bits = false

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block ="custom"
command = "echo 🎵"

[[block]]
block = "custom"
command = ''' cat ~/np.txt '''

# [[block]]
# block = "networkmanager"
# on_click = "tilix -e nmtui"
# primary_only = true

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{max}° max"
# format = "{min}° min, {max}° max, {average}° avg"
# chip = "*-isa-*"

#[[block]]
#block = "pomodoro"
#length = 25
#break_length = 5
#message = "Take a break!"
#break_message = "Back to work!"
#use_nag = false

# [[block]]
# block = "uptime"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "orage"

# [[block]]
# block = "time"
# format = "UTC:%R"
# timezone = "UTC"
# interval = 60
# on_click = "orage"

# [[block]]
# block = "backlight"

# [[block]]
# block = "battery"
# interval = 10
# format = "{percentage}%"

# [[block]]
# block = "toggle"
# text = "DV"
# command_state = "xrandr | grep HDMI2\\ connected\\ 1080 | grep -v eDP1"
# command_on = "~/.screenlayout/vertical.sh"
# command_off = "~/.screenlayout/laptop.sh"
# interval = 5

# [[block]]
# block = "toggle"
# text = "DH"
# command_state = "xrandr | grep HDMI2\\ connected\\ 2560 | grep -v eDP1"
# command_on = "~/.screenlayout/horizon.sh"
# command_off = "~/.screenlayout/laptop.sh"
# interval = 5

#[[block]]
#block = "custom"
#interval = 999999
#command = "echo '\uF011'"
#on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"
