require "user.plugins"
require "user.options"
require "user.status"
require "user.functions"
require "user.keymaps"
require "user.autocommands"
require "user.lsp"
require "user.rust"
require "user.python"
-- require "user.ruff"
-- require "user.copilot"
require "user.todo-comments"
require "user.window-picker-config"
require "user.cybu"
require "user.scrollbar"
require "user.lazy"
