= Increment and Decrement for Kakoune

This plugin provides a command,
`inc-dec-modify-numbers`,
which will apply an operator to every recognised number in the selection.
It's mostly useful for setting up keybindings
to increment or decrement numbers.

== Example configuration

For a configuration that works just like Vim,
add the following mappings to your `kakrc`:

----
map global normal <c-a> ': inc-dec-modify-numbers + %val{count}<ret>'
map global normal <c-x> ': inc-dec-modify-numbers - %val{count}<ret>'
----

With these mappings,
`<c-a>` and `<c-x>` will increment and decrement the selection by one,
while `5<c-a>` and `5<c-x>` will increment and decrement by five.

See <<mapping#description,`:doc mapping`>> for more about mappings.

== Number syntaxes

Almost all numbers you'll see in a text editor like Kakoune are decimal,
although sometimes you'll come across hexadecimal numbers.
Decimal numbers are generally written with ASCII digits,
possibly including leading 0s,
while hexadecimal numbers are indicated with a leading `0x`.

Very rarely, you might come across octal (base 8) numbers.
In modern programming languages,
these are written with a leading `0o`,
making them unique and unambiguous,
but in older languages these are written with a leading `0`,
making them look exactly like zero-padded decimal numbers.

A number with a leading `0` is much more likely
to be a zero-padded decimal number than an octal number
(since octal is rarely used,
and zero-padded decimal numbers occur in timestamps and serial numbers)
so this plugin will use a leading zero as an indication
that the original number width should be preserved.

However, the older octal syntax is still widely supported
for compatibility purposes,
so this plugin avoids _adding_ a leading zero
if one is not already present.
This means that if you increment `099` to `100`
then decrement it, you'll get `99`
(the leading 0 is lost)
but I think that's better than introducing `099` in a file
where that would be a syntax error
(because `9` is not a valid octal digit).
