wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        SaoPaulo: "America/Sao_Paulo"
        Raleigh: "America/New_York"
        Portugal: "Europe/Lisbon"
        Czech: "Europe/Prague"
        Poland: "Europe/Warsaw"
        UTC: "Etc/UTC"
      position:
        top: 4
        left: 0
        height: 2
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "World Time"
      type: "clocks"
    # feedreader:
    #   enabled: true
    #   feeds:
    #   - http://wtfutil.com/blog/index.xml
    #   feedLimit: 10
    #   position:
    #     top: 1
    #     left: 2
    #     width: 2
    #     height: 1
    #   updateInterval: 14400
    # ipinfo:
    #   colors:
    #     name: "lightblue"
    #     value: "white"
    #   enabled: true
    #   position:
    #     top: 2
    #     left: 2
    #     height: 1
    #     width: 1
    #   refreshInterval: 150
    # power:
    #   enabled: true
    #   position:
    #     top: 2
    #     left: 3
    #     height: 1
    #     width: 1
    #   refreshInterval: 15
    #   title: "⚡️"
    # textfile:
    #   enabled: true
    #   filePath: "~/.config/wtf/config.yml"
    #   format: true
    #   position:
    #     top: 0
    #     left: 0
    #     height: 4
    #     width: 1
    #   refreshInterval: 30
    #   wrapText: false
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 3
      refreshInterval: 30
      type: cmdrunner
    # docker:
    #   type: docker
    #   enabled: true
    #   labelColor: lightblue
    #   position:
    #     top: 0
    #     left: 0
    #     height: 4
    #     width: 2
    #   refreshInterval: 5
    exchangerates:
      refreshInterval: 900
      enabled: true
      focusable: false
      position:
        top: 4
        left: 1
        width: 1
        height: 2
      precision: 3
      rates:
        BRL:
          - "USD"
          - "EUR"
        USD:
          - "BRL"
        EUR:
          - "BRL"
      title: "💰 Rates"
    github:
      apiKey: GITHUB_API_KEY_HERE
      baseURL: ""
      customQueries:
        othersPRs:
          title: "Others Pull Requests"
          filter: "is:open is:pr -author:rochacbruno"
        bugs:
          title: "Bugs"
          filter: "is:issue is:open label:bug"
      enabled: true
      enableStatus: true
      position:
        top: 0
        left: 3
        height: 2
        width: 2
      refreshInterval: 300
      repositories:
        - "rochacbruno/dynaconf"
      uploadURL: ""
      username: "rochacbruno"

    github2:
      type: github
      apiKey: GITHUB_API_KEY_HERE
      baseURL: ""
      customQueries:
        othersPRs:
          title: "Others Pull Requests"
          filter: "is:open is:pr -author:rochacbruno"
      enabled: true
      enableStatus: true
      position:
        top: 0
        left: 1
        height: 2
        width: 2
      refreshInterval: 300
      repositories:
        - "ansible/galaxy_ng"
      uploadURL: ""
      username: "rochacbruno"


    gcal:
      colors:
        title: "red"
        eventTime: "lightblue"
        description: "yellow"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "rochacbruno@redhat.com"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: false
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 300
      secretFile: "~/google/credentials.json"
      showDeclined: true
      showEndTime: false
      timezone: "America/Sao_Paulo"
      withLocation: true

    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 2
        left: 1
        height: 1
        width: 3
      storyType: top
      refreshInterval: 300

    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 2
        left: 4
        height: 2
        width: 1
      refreshInterval: 3600

    prettyweather:
      enabled: false
      city: "Guarulhos"
      position:
        top: 4
        left: 2
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"

    # weather:
    #   args: ["-w"]
    #   cmd: "inxi"
    #   enabled: true
    #   type: "cmdrunner"
    #   position:
    #     top: 4
    #     left: 2
    #     height: 2
    #     width: 1
    #   refreshInterval: 100

    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 4
        left: 2
        height: 2
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true

#     spotify:
#       enabled: true
#       colors:
#         label: "green"
#         text: "white"
#       position:
#         top: 4
#         left: 2
#         height: 2
#         width: 1
#       refreshInterval: 0
#

    feedreader:
      enabled: true
      feeds:
      - https://issues.redhat.com/sr/jira.issueviews:searchrequest-rss/temp/SearchRequest.xml?jqlQuery=project+%3D+AAH+AND+status+%21%3D+Done++AND+assignee+%3D+rochacbruno+ORDER+BY+priority+DESC%2C+updated+DESC&tempMax=1000
      feedLimit: 10
      title: "Jira Issues"
      position:
        top: 4
        left: 3
        height: 2
        width: 2
      refreshInterval: 600
