[[snippets]]
  description = "Run shell plus on galaxy django container"
  command = "./compose run --rm api /bin/bash -c \"pip install ipython ipdb django-extensions && ./entrypoint.sh manage shell_plus\""
  output = ""
